
USE `peru`;

DROP TABLE IF EXISTS `peru`.`00_SAMPLE` ;

CREATE TABLE IF NOT EXISTS `peru`.`00_SAMPLE` (
	    `ARRAY_CODE`    VARCHAR(50) NOT NULL,
	    `INTERNAL_CODE` VARCHAR(50) NOT NULL,
	    `POPULATION`    VARCHAR(50) NOT NULL,
	    `DEPARTMENT`    VARCHAR(50) NOT NULL,
	    `STATUS`        VARCHAR(50) NOT NULL,
	    PRIMARY KEY (`ARRAY_CODE`)
	)
ENGINE = InnoDB;


