
USE `peru`;
-- 02-up-vep-ex-common-var-1-conseq.py
DROP TABLE IF EXISTS `peru`.`02_UP_VEP_EX_COMMON_VAR_1_CONSEQ` ;

CREATE TABLE IF NOT EXISTS `peru`.`02_UP_VEP_EX_COMMON_VAR_1_CONSEQ` (
    `ID_02_UP_VEP_EX_COMMON_VAR_1_CONSEQ` INT(11) NOT NULL AUTO_INCREMENT,
    `Uploaded_variation` TEXT,
    `Chromosome` VARCHAR(5) NOT NULL,
    `Chr_Start`  INT(25) NOT NULL,
    `Chr_End`    INT(25) NOT NULL,
    `Allele`          TEXT,
    `Consequence`     TEXT,
    `IMPACT`          VARCHAR(25) NOT NULL,
    `SYMBOL`          TEXT,
    `Gene`            TEXT,
    `Feature_type`    TEXT,   
    `Feature`         TEXT,
    `BIOTYPE`         TEXT,
    `EXON`            TEXT,
    `INTRON`          TEXT,
    `HGVSc`           TEXT,
    `HGVSp`           TEXT,
    `cDNA_position`   TEXT,   
    `CDS_position`    TEXT,
    `Protein_position` TEXT,
    `Amino_acids`     TEXT,
    `Codons`          TEXT,
    `Existing_variation` TEXT,
    `DISTANCE`        TEXT,
    `STRAND`          TEXT,
    `FLAGS`           TEXT,
    `SYMBOL_SOURCE`   TEXT,   
    `HGNC_ID`         TEXT, 
    `SIFT`            TEXT,
    `PolyPhen`        TEXT,
    `AF`              TEXT,
    `gnomADg_AF`       TEXT,   
    `gnomADg_AFR_AF`   TEXT, 
    `gnomADg_AMI_AF`  TEXT,
    `gnomADg_AMR_AF`   TEXT,
    `gnomADg_ASJ_AF`   TEXT,
    `gnomADg_EAS_AF`   TEXT,
    `gnomADg_FIN_AF`   TEXT,
    `gnomADg_MID_AF`  TEXT,
    `gnomADg_NFE_AF`   TEXT, 
    `gnomADg_OTH_AF`   TEXT,
    `gnomADg_SAS_AF`   TEXT,
    `FREQS`            TEXT,
    `CLIN_SIG`        TEXT,
    `SOMATIC`         TEXT,
    `PHENO`           TEXT,
    `MOTIF_NAME`      TEXT,
    `MOTIF_POS`       TEXT,
    `HIGH_INF_POS`    TEXT,
    `MOTIF_SCORE_CHANGE`  TEXT,
    `TRANSCRIPTION_FACTORS`   TEXT,
    `CADD_PHRED`      TEXT,
    `CADD_RAW`        TEXT,
    `LOEUF`         TEXT,
    PRIMARY KEY (`ID_02_UP_VEP_EX_COMMON_VAR_1_CONSEQ`),
    INDEX (`Chromosome`,`Chr_Start`,`Chr_End`,`IMPACT`)
)
ENGINE = InnoDB;
