
DROP TABLE IF EXISTS `peru`.`03_01_VEP_CONSEQUENCE_SEVERITY_RANK`;
CREATE TABLE 03_01_VEP_CONSEQUENCE_SEVERITY_RANK (
    Impact VARCHAR(50),
    Consequence VARCHAR(255),
    Severity_Score INT,
    PRIMARY KEY (Impact,Consequence)
);


INSERT INTO 03_01_VEP_CONSEQUENCE_SEVERITY_RANK (Impact, Consequence, Severity_Score) VALUES
('High Impact', 'transcript_ablation', 1),
('High Impact', 'splice_acceptor_variant', 2),
('High Impact', 'splice_donor_variant', 3),
('High Impact', 'stop_gained', 4),
('High Impact', 'frameshift_variant', 5),
('High Impact', 'stop_lost', 6),
('High Impact', 'start_lost', 7),
('High Impact', 'transcript_amplification', 8),
('High Impact', 'inframe_insertion', 9),
('High Impact', 'inframe_deletion', 10),
('High Impact', 'missense_variant', 11),
('High Impact', 'protein_altering_variant', 12),
('High Impact', 'splice_region_variant', 13),
('High Impact', 'incomplete_terminal_codon_variant', 14),
('High Impact', 'start_retained_variant', 15),
('High Impact', 'stop_retained_variant', 16),
('High Impact', 'synonymous_variant', 17),
('High Impact', 'coding_sequence_variant', 18),
('Moderate Impact', 'regulatory_region_ablation', 19),
('Moderate Impact', 'regulatory_region_amplification', 20),
('Moderate Impact', 'TF_binding_site_ablation', 21),
('Moderate Impact', 'TF_binding_site_amplification', 22),
('Moderate Impact', 'regulatory_region_variant', 23),
('Moderate Impact', 'TF_binding_site_variant', 24),
('Moderate Impact', 'mature_miRNA_variant', 25),
('Moderate Impact', '5_prime_UTR_variant', 26),
('Moderate Impact', '3_prime_UTR_variant', 27),
('Low Impact', 'non_coding_transcript_exon_variant', 28),
('Low Impact', 'intron_variant', 29),
('Low Impact', 'NMD_transcript_variant', 30),
('Low Impact', 'non_coding_transcript_variant', 31),
('Low Impact', 'upstream_gene_variant', 32),
('Low Impact', 'downstream_gene_variant', 33),
('Low Impact', 'TFBS_ablation', 34),
('Low Impact', 'TFBS_amplification', 35),
('Low Impact', 'TF_binding_site_variant', 36),
('Low Impact', 'regulatory_region_ablation', 37),
('Low Impact', 'regulatory_region_amplification', 38),
('Low Impact', 'feature_elongation', 39),
('Low Impact', 'regulatory_region_variant', 40),
('Low Impact', 'feature_truncation', 41),
('Low Impact', 'intergenic_variant', 42),
('Modifier Impact', 'incomplete_terminal_codon_variant', 43),
('Modifier Impact', 'start_retained_variant', 44),
('Modifier Impact', 'stop_retained_variant', 45),
('Modifier Impact', 'synonymous_variant', 46),
('Modifier Impact', 'coding_sequence_variant', 47),
('Modifier Impact', 'mature_miRNA_variant', 48),
('Modifier Impact', '5_prime_UTR_variant', 49),
('Modifier Impact', '3_prime_UTR_variant', 50),
('Modifier Impact', 'non_coding_transcript_exon_variant', 51),
('Modifier Impact', 'intron_variant', 52),
('Modifier Impact', 'NMD_transcript_variant', 53),
('Modifier Impact', 'non_coding_transcript_variant', 54),
('Modifier Impact', 'upstream_gene_variant', 55),
('Modifier Impact', 'downstream_gene_variant', 56),
('Modifier Impact', 'TFBS_ablation', 57),
('Modifier Impact', 'TFBS_amplification', 58),
('Modifier Impact', 'TF_binding_site_variant', 59),
('Modifier Impact', 'regulatory_region_ablation', 60),
('Modifier Impact', 'regulatory_region_amplification', 61),
('Modifier Impact', 'feature_elongation', 62),
('Modifier Impact', 'regulatory_region_variant', 63),
('Modifier Impact', 'feature_truncation', 64),
('Modifier Impact', 'intergenic_variant', 65);


